package httpapi

import "net/http"

func (s *Server) openapi(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, map[string]any{
		"openapi": "3.0.3",
		"info":    map[string]any{"title": "ml-ai-ops-platform API", "version": "0.1.0"},
		"paths": map[string]any{
			"/api/v1/health":                       map[string]any{"get": map[string]any{"summary": "Gateway health"}},
			"/api/v1/me":                           map[string]any{"get": map[string]any{"summary": "Caller identity, roles and effective permissions"}},
			"/api/v1/admin/users":                  map[string]any{"get": map[string]any{"summary": "List user access profiles (admin only)"}},
			"/api/v1/admin/resource-profiles":      map[string]any{"get": map[string]any{"summary": "List canonical compute and memory profiles (admin only)"}},
			"/api/v1/admin/users/{subject}":        map[string]any{"put": map[string]any{"summary": "Provision user access and quotas (admin only)"}, "delete": map[string]any{"summary": "Revoke user access (admin only)"}},
			"/api/v1/access-requests":              map[string]any{"get": map[string]any{"summary": "List caller access requests"}, "post": map[string]any{"summary": "Request platform access"}},
			"/api/v1/admin/access-requests":        map[string]any{"get": map[string]any{"summary": "List access requests (admin only)"}},
			"/api/v1/admin/access-requests/{id}":   map[string]any{"patch": map[string]any{"summary": "Approve or reject an access request (admin only)"}},
			"/api/v1/settings/tokens":              map[string]any{"get": map[string]any{"summary": "List personal API keys"}, "post": map[string]any{"summary": "Create a scoped personal API key"}},
			"/api/v1/settings/tokens/{id}":         map[string]any{"delete": map[string]any{"summary": "Revoke a personal API key"}},
			"/api/v1/blogs":                        map[string]any{"get": map[string]any{"summary": "List published engineering blog posts"}},
			"/api/v1/blogs/{slug}":                 map[string]any{"get": map[string]any{"summary": "Read a published engineering blog post"}},
			"/api/v1/admin/blogs":                  map[string]any{"get": map[string]any{"summary": "List all blog drafts and posts"}, "post": map[string]any{"summary": "Create a blog post"}},
			"/api/v1/admin/blogs/{id}":             map[string]any{"put": map[string]any{"summary": "Update or publish a blog post"}, "delete": map[string]any{"summary": "Delete a blog post"}},
			"/api/v1/dashboard":                    map[string]any{"get": map[string]any{"summary": "Workspace summary"}},
			"/api/v1/onboarding/readiness":         map[string]any{"get": map[string]any{"summary": "Onboarding readiness"}},
			"/api/v1/projects":                     map[string]any{"get": map[string]any{"summary": "List projects"}, "post": map[string]any{"summary": "Create project"}},
			"/api/v1/projects/{id}":                map[string]any{"get": map[string]any{"summary": "Get project metadata"}},
			"/api/v1/projects/{id}/repository":     map[string]any{"put": map[string]any{"summary": "Connect a Git repository to a project"}},
			"/api/v1/pipelines/definitions":        map[string]any{"get": map[string]any{"summary": "List reusable pipeline definitions"}, "post": map[string]any{"summary": "Create a pipeline definition"}},
			"/api/v1/pipelines/definitions/{id}":   map[string]any{"get": map[string]any{"summary": "Get pipeline definition"}, "put": map[string]any{"summary": "Update pipeline definition"}},
			"/api/v1/pipelines/runs":               map[string]any{"get": map[string]any{"summary": "List pipeline runs"}},
			"/api/v1/pipelines/submit":             map[string]any{"post": map[string]any{"summary": "Submit pipeline"}},
			"/api/v1/pipelines/runs/{id}":          map[string]any{"get": map[string]any{"summary": "Pipeline steps and logs"}},
			"/api/v1/pipelines/runs/{id}/cancel":   map[string]any{"post": map[string]any{"summary": "Cancel a pipeline run"}},
			"/api/v1/pipelines/runs/{id}/retry":    map[string]any{"post": map[string]any{"summary": "Retry a pipeline run"}},
			"/api/v1/pipelines/runs/{id}/steps":    map[string]any{"post": map[string]any{"summary": "Report pipeline step state"}},
			"/api/v1/components":                   map[string]any{"get": map[string]any{"summary": "List platform component health"}},
			"/api/v1/catalog":                      map[string]any{"get": map[string]any{"summary": "Browse models, features, agents and tools"}},
			"/api/v1/features":                     map[string]any{"get": map[string]any{"summary": "List feature views"}, "post": map[string]any{"summary": "Apply a feature view"}},
			"/api/v1/features/{name}/materialized": map[string]any{"post": map[string]any{"summary": "Report feature materialization"}},
			"/api/v1/storage/buckets":              map[string]any{"get": map[string]any{"summary": "List object-store buckets"}},
			"/api/v1/storage/objects":              map[string]any{"get": map[string]any{"summary": "List objects and prefixes"}},
			"/api/v1/storage/object":               map[string]any{"get": map[string]any{"summary": "Preview an object"}},
			"/api/v1/prompts":                      map[string]any{"get": map[string]any{"summary": "List Langfuse prompts"}},
			"/api/v1/events":                       map[string]any{"get": map[string]any{"summary": "Stream platform updates using server-sent events"}},
			"/api/v1/realtime":                     map[string]any{"get": map[string]any{"summary": "Read real-time processing statistics"}},
			"/api/v1/realtime/{demo}":              map[string]any{"post": map[string]any{"summary": "Report real-time demo statistics"}},
			"/api/v1/functions":                    map[string]any{"get": map[string]any{"summary": "List serverless functions"}, "post": map[string]any{"summary": "Deploy a serverless function"}},
			"/api/v1/functions/{name}":             map[string]any{"delete": map[string]any{"summary": "Remove a serverless function"}},
			"/api/v1/functions/{name}/invoke":      map[string]any{"post": map[string]any{"summary": "Invoke a serverless function"}},
			"/api/v1/models":                       map[string]any{"get": map[string]any{"summary": "List registered models"}, "post": map[string]any{"summary": "Register a model"}},
			"/api/v1/models/{id}/promote":          map[string]any{"post": map[string]any{"summary": "Promote a model"}},
			"/api/v1/models/{id}/deploy":           map[string]any{"post": map[string]any{"summary": "Deploy a model"}},
			"/api/v1/models/{id}/rollback":         map[string]any{"post": map[string]any{"summary": "Roll back a model deployment"}},
			"/api/v1/models/{id}/predict":          map[string]any{"post": map[string]any{"summary": "Send a prediction request"}},
			"/api/v1/agents":                       map[string]any{"get": map[string]any{"summary": "List agents"}, "post": map[string]any{"summary": "Deploy an agent"}},
			"/api/v1/agents/{id}/traffic":          map[string]any{"put": map[string]any{"summary": "Update agent canary traffic"}},
			"/api/v1/agents/{id}/invoke":           map[string]any{"post": map[string]any{"summary": "Invoke an agent"}},
			"/api/v1/agents/{id}/sessions":         map[string]any{"get": map[string]any{"summary": "List agent sessions"}},
			"/api/v1/agents/{id}/traces":           map[string]any{"get": map[string]any{"summary": "List agent traces"}},
			"/api/v1/agents/{id}/usage":            map[string]any{"get": map[string]any{"summary": "Read agent token and cost usage"}},
			"/api/v1/tools":                        map[string]any{"get": map[string]any{"summary": "List tools"}, "post": map[string]any{"summary": "Register a tool"}},
			"/api/v1/connections":                  map[string]any{"get": map[string]any{"summary": "List connections"}, "post": map[string]any{"summary": "Create a secret-backed connection"}},
			"/api/v1/connections/{id}/test":        map[string]any{"post": map[string]any{"summary": "Test a platform connection"}},
			"/api/v1/audit":                        map[string]any{"get": map[string]any{"summary": "List audit events"}},
			"/api/v1/traces":                       map[string]any{"post": map[string]any{"summary": "Record an agent trace"}},
		},
	})
}
